{{- if .Values.prometheusRule.smartmon_sata }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: smartmon-sata-rules
  namespace: monitoring-{{ .Values.customerid }}
spec:
  {{- $.Files.Get "rules/smartmon_sata.yaml" | nindent 4 }}
{{- end }}
