{{- if .Values.prometheusRule.zfs }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: zfs
  namespace: monitoring-{{ .Values.customerid }}
spec:
  {{- $.Files.Get "rules/zfs.yaml" | nindent 4 }}
{{- end }}
