{{- if (.Values.global.capa).enableClusterAutoscaler }}
{{- range $index, $nodeGroup := $.Values.nodeGroups }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: {{ printf "%s-%s" $.Values.global.clusterName $nodeGroup.name }}
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
          name: '{{"{{"}} ds.meta_data.local_hostname {{"}}"}}'
          {{- if $nodeGroup.taints }}
          taints: {{- toYaml $nodeGroup.taints | nindent 8 }}
          {{- end }}
{{- end }}
{{- end }}
