{{- if (.Values.global.capa).autoScaler }}
{{- range $index, $nodeGroup := $.Values.nodeGroups }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfig
metadata:
  name: {{ printf "%s-%s" $.Values.global.clusterName $nodeGroup.name }}
spec:
  joinConfiguration:
    nodeRegistration:
      kubeletExtraArgs:
        cloud-provider: external
      name: '{{"{{"}} ds.meta_data.local_hostname {{"}}"}}'
      {{- if $nodeGroup.taints }}
      taints: {{- toYaml $nodeGroup.taints | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
