apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  {{ if (.Values.postgres).recover }}
  name: mattermost-pgsql-recover
  {{ else }}
  name: mattermost-pgsql
  {{ end }}
spec:
  instances: {{ ((.Values.postgres).instance) | default 1 }}
  {{ if (.Values.postgres).recover }}
  bootstrap:
    recovery: mattermost-pgsql
  {{ else }}
  bootstrap:
    initdb:
      database: mattermost
      owner: mattermost
  {{ end }}
  resources:
    limits:
      memory: {{ (((.Values.postgres).resources).limits).memory | default "800Mi" }}
    requests:
      memory: {{ (((.Values.postgres).resources).requests).memory | default "500Mi" }}
      cpu: {{ (((.Values.postgres).resources).requests).cpu | default "100m" }}
  storage:
    size: {{ (.Values.postgres).size }}
    {{- if (.Values.postgres).storageClass }}
    storageClass: {{ (.Values.postgres).storageClass }}
    {{- end }}
  {{- if (.Values.postgres).recover }}
  externalClusters:
    name: mattermost-pgsql
    barmanObjectStore:
      destinationPath: {{ ((.Values.postgres).backup).destinationPath }}
      endpointURL: {{ ((.Values.postgres).backup).endpointURL }}
      {{- if eq ((.Values.postgres).backup).cloud "aws" }}
      s3Credentials:
        accessKeyId:
          name: mattermost-pgsql-backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: mattermost-pgsql-backup-creds
          key: ACCESS_SECRET_KEY
      {{- end }}
      {{- if eq ((.Values.postgres).backup).cloud "azure" }}
      azureCredentials:
        connectionString:
          name: mattermost-pgsql-backup-creds
          key: AZURE_CONNECTION_STRING
        storageAccount:
          name: mattermost-pgsql-backup-creds
          key: AZURE_STORAGE_ACCOUNT
        storageKey:
          name: mattermost-pgsql-backup-creds
          key: AZURE_STORAGE_KEY
        storageSasToken:
          name: mattermost-pgsql-backup-creds
          key: AZURE_STORAGE_SAS_TOKEN
      {{- end }}
        wal:
          maxParallel: 8
  {{- end }}
  {{- if (.Values.postgres).backup }}
  backup:
    barmanObjectStore:
      destinationPath: {{ ((.Values.postgres).backup).destinationPath }}
      endpointURL: {{ ((.Values.postgres).backup).endpointURL }}
      {{- if eq ((.Values.postgres).backup).cloud "aws" }}
      s3Credentials:
        accessKeyId:
          name: mattermost-pgsql-backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: mattermost-pgsql-backup-creds
          key: ACCESS_SECRET_KEY
      {{- end }}
      {{- if eq ((.Values.postgres).backup).cloud "azure" }}
      azureCredentials:
        connectionString:
          name: mattermost-pgsql-backup-creds
          key: AZURE_CONNECTION_STRING
        storageAccount:
          name: mattermost-pgsql-backup-creds
          key: AZURE_STORAGE_ACCOUNT
        storageKey:
          name: mattermost-pgsql-backup-creds
          key: AZURE_STORAGE_KEY
        storageSasToken:
          name: mattermost-pgsql-backup-creds
          key: AZURE_STORAGE_SAS_TOKEN
      {{- end }}
      wal:
        compression: gzip
        encryption: AES256
    retentionPolicy: "30d"
  {{ end  }}
