name: promtool

"on":
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  promtool:
    name: Prometheus rule test
    runs-on: ubuntu-latest
    container:
      image: ${{ secrets.HARBOR_REGISTRY }}/${{ vars.KUBEAID_CI_IMAGE }}:${{ vars.KUBEAID_CI_TAG }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: promtool
        working-directory: argocd-helm-charts/prometheus-linuxaid/tests
        run: promtool test rules *.yaml

      - name: prometheus mixins
        working-directory: build/kube-prometheus/mixins
        run: |
          for dir in */; do
            if [ -f "$dir""prometheus.yaml" ]; then
              promtool check rules "$dir""prometheus.yaml"
            else
              echo "Did not find 'prometheus.yaml' in '$dir'"
              echo "Please generate prometheus.yaml for your new mixin"
              exit 1
            fi
          done
