{{ if (.Values.postgresql.logicalBackup).enabled  }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-logical-backup
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  schedule: {{ (.Values.postgresql.logicalBackup).schedule | default "30 00 * * *" }}
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
  {{ toYaml (.Values.postgresql.logicalBackup).annotations | indent 10 }}
        spec:
          containers:
            - name: logical-backup
              image: ghcr.io/obmondo/logical-backup:1.0.2
              imagePullPolicy: IfNotPresent
              env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.namespace
                - name: PGHOST
                  value: "{{ .Values.postgresql.host }}"
                - name: PGPORT
                  value: "{{ .Values.postgresql.port | default 5432 }}"
                - name: PGUSER
                  value: {{ .Values.postgresql.user | default "api" }}
                - name: PGDATABASE
                  value: {{ .Values.postgresql.db }}
                - name: CLUSTER_NAME_LABEL
                  value: {{ (.Values.postgresql.logicalBackup).pgOperatorClusterName | default "api-postgresql" }}
                - name: AWS_ACCESS_KEY_ID
                  value: {{ (.Values.postgresql.logicalBackup).s3accesskeyid }}
                - name: PG_VERSION
                  value: "{{ (.Values.postgresql.logicalBackup).pgversion | default 16 }}"
                - name: LOGICAL_BACKUP_S3_ENDPOINT
                  value: {{ (.Values.postgresql.logicalBackup).s3endpoint }}
                - name: LOGICAL_BACKUP_PROVIDER
                  value: "s3"
                - name: LOGICAL_BACKUP_S3_BUCKET_SCOPE_SUFFIX
                  value: {{ (.Values.postgresql.logicalBackup).s3bucketscopesuffix | default "logicalBackup" }}
                - name: LOGICAL_BACKUP_S3_REGION
                  value: {{ (.Values.postgresql.logicalBackup).s3region }}
                - name: LOGICAL_BACKUP_S3_BUCKET
                  value: {{ (.Values.postgresql.logicalBackup).s3bucket }}
                - name: LOGICAL_BACKUP_S3_RETENTION_TIME
                  value: {{ (.Values.postgresql.logicalBackup).retention }}
                - name: POSTGRES_OPERATOR
                  value: cngp

                {{- toYaml .Values.postgresql.extraEnvVars | nindent 16 }}

              resources:
                limits:
                  cpu: 100m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
              securityContext:
                allowPrivilegeEscalation: true
                privileged: false
                readOnlyRootFilesystem: false
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          terminationGracePeriodSeconds: 300
{{ end }}