zfs-localpv:
  zfsNode:
    nodeSelector:
      disk: nvme
    tolerations: []
    securityContext: {}
    labels: {}
    priorityClass:
      create: true
      name: zfs-csi-node-critical
  # zfsExporter Confiration
  zfsExporter:
    enable: true
    serviceMonitor:
      enabled: true
      path: /metrics
      interval: 10s
    name: zfs-exporter
    portDefination:
      name: metrics
      port: 9134
    image:
      # Make sure that registry name end with a '/'.
      # For example : registry.k8s.io/ is a correct value here and quay.io is incorrect
      registry: harbor.obmondo.com/
      repository: obmondo/zfs_exporter
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: v2.3.4_1 # Need to replace
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 50m
        memory: 100Mi
  # zfsController contains the configurables for
  # the zfs controller statefulset
  zfsController:
    nodeSelector:
      disk: nvme
    tolerations: []
    securityContext: {}
    priorityClass:
      create: true
      name: zfs-csi-controller-critical


# poolname must be provided and should be same as the zfs pool created on node for storageclass to be correctly configured.
storageClass:
  enabled: false
