kafka:
  - name: strimzi-kafka
    kafka:
      replicas: 1
      authorization:
        type: simple
      listeners:
        - name: internal
          port: 9094
          type: internal
          tls: false
          authentication:
            type: scram-sha-512
      storage:
        type: jbod
        volumes:
        - id: 0
          class: rook-ceph-block
          type: persistent-claim
          size: 1Gi
          deleteClaim: false
      config:
        offsets.topic.replication.factor: 1
        transaction.state.log.replication.factor: 1
        transaction.state.log.min.isr: 1
        default.replication.factor: 1
        min.insync.replicas: 1
    zookeeper:
      replicas: 3
      storage:
        type: persistent-claim
        class: rook-ceph-block
        size: 1Gi
        deleteClaim: false

kafkaTopics:
  - topicName: my-topic
    cluster: strimzi-kafka
    partitions: 3
    replicas: 1

kafkaUser:
  - name: my-user
    cluster: strimzi-kafka
    authentication:
      type: scram-sha-512
    authorization:
      type: simple
      acls:
        - type: allow
          resource:
            type: topic
            name: my-topic
            patternType: literal
          host: "*"
          operations:
            - Read
            - Write
        - type: allow
          resource:
            type: group
            name: my-group
            patternType: literal
          host: "*"
          operations:
            - Read

ingress:
  enable: false
  name: kafka
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: prefix
            backend:
              service:
                name: strimzi-kafka-kafka-internal-bootstrap
                port:
                  number: 9094
  tls:
    enable: false
    config:
      - hosts:
        - localhost
        secretName: local-host-tls
