kafka:
  - name: strimzi-kafka
    kafka:
      replicas: 1
      authorization:
        type: simple
      listeners:
        - name: ingress
          port: 9094
          type: ingress
          tls: true
          authentication:
            type: tls
          configuration:
            bootstrap:
              host: localhost
              annotations:
                kubernetes.io/ingress.class: nginx
            brokers:
            - id: 0
              host: kafka-0
              annotations:
                kubernetes.io/ingress.class: nginx
            - id: 1
              host: kafka-1
              annotations:
                kubernetes.io/ingress.class: nginx
            - id: 2
              host: kafka-2
              annotations:
                kubernetes.io/ingress.class: nginx
            class: nginx
      storage:
        type: jbod
        volumes:
        - id: 0
          class: rook-ceph-block
          type: persistent-claim
          size: 1Gi
          deleteClaim: false
      config:
        offsets.topic.replication.factor: 1
        transaction.state.log.replication.factor: 1
        transaction.state.log.min.isr: 1
        default.replication.factor: 1
        min.insync.replicas: 1
    zookeeper:
      replicas: 3
      storage:
        type: persistent-claim
        class: rook-ceph-block
        size: 1Gi
        deleteClaim: false
