cert-manager:
  podAnnotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  installCRDs: true
  clusterResourceNamespace: cert-manager
  global:
    leaderElection:
      namespace: cert-manager
    revisionHistoryLimit: 0
  prometheus:
    enabled: true
    servicemonitor:
      enabled: true
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 4m
      memory: 64Mi
  cainjector:
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 1m
        memory: 64Mi
  webhook:
    resources:
      limits:
        memory: 32Mi
      requests:
        cpu: 1m
        memory: 16Mi

issuer:
  name: letsencrypt
  enabled: false
  production: false
  preferredChain: null
  solvers:
    - type: http
      http01:
        ingress:
          ingressClassName: traefik-cert-manager

networkpolicies: false
enableCertificateOwnerRef: true
