apiVersion: v2
appVersion: v0.13.1
dependencies:
- condition: minio.enabled
  name: minio
  repository: https://charts.min.io
  version: 5.3.0
description: Logs, Metrics and Traces, Dashboards, RUM, Error tracking, Session replay
  etc. Elasticsearch API compatibility.
maintainers:
- email: hello@openobserve.ai
  name: OpenObserve
  url: https://openobserve.ai
name: openobserve-standalone
type: application
version: 0.13.5
