{{ if .Values.networkpolicies }}
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.default
  namespace: cert-manager
spec:
  order: 1000
  types:
  - Ingress
  - Egress
  ingress:
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: projectcalico.org/name == 'monitoring'
      selector: app.kubernetes.io/name == 'prometheus'
    destination:
      ports:
      - 9402
  - action: Log
  - action: Deny
  egress:
  - action: Allow
    protocol: UDP
    destination:
      ports:
      - 53
      namespaceSelector: projectcalico.org/name == 'kube-system'
      selector: k8s-app == 'kube-dns'
  - action: Allow
    protocol: TCP
    destination:
      ports:
      - 53
      namespaceSelector: projectcalico.org/name == 'kube-system'
      selector: k8s-app == 'kube-dns'
  - action: Log
  - action: Deny
{{ end }}
