apiVersion: v2
name: openobserve
version: 0.13.4
dependencies:
  - name: openobserve
    version: 0.13.5
    repository: https://charts.openobserve.ai/
  - name: openobserve-standalone
    version: 0.13.5
    repository: https://charts.openobserve.ai/
  - name: openobserve-collector
    version: 0.3.14
    repository: https://charts.openobserve.ai/
