{{- if .Values.storageClass.enabled -}}
{{- range $className, $classOptions := .Values.storageClass }}
{{- if ne $className "enabled" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $className }}
allowVolumeExpansion: {{ $classOptions.allowVolumeExpansion | default true }}
parameters:
  recordsize: {{ $classOptions.recordsize | default "4k" | quote }}
  thinprovision: {{ $classOptions.thinprovision | default "no" | quote }}
  compression: {{ $classOptions.compression | default "off" | quote }}
  dedup: {{ $classOptions.dedup | default "off" | quote }}
  fstype: {{ $classOptions.fstype | default "zfs" | quote }}
  poolname: {{ required "poolName is required for storage class " $classOptions.poolName | quote }}
  shared: {{ $classOptions.shared | default "no" | quote }}
provisioner: zfs.csi.openebs.io
reclaimPolicy: {{ $classOptions.reclaimPolicy | default "Delete" }}
---
{{- end -}}
{{- end -}}
{{- end -}}
