{{- if .Values.storageClass.enabled -}}
{{- range $className, $classOptions := .Values.storageClass }}
{{- if ne $className "enabled" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $className }}
{{- if $classOptions.allowVolumeExpansion }}
allowVolumeExpansion: {{ $classOptions.allowVolumeExpansion }}
{{- end }}
parameters:
  recordsize: {{ $classOptions.recordsize | default "4k" }}
  {{- if $classOptions.thinprovision }}
  thinprovision: {{ $classOptions.thinprovision | quote }}
  {{- end }}
  compression: {{ $classOptions.compression | default "off" | quote }}
  {{- if $classOptions.dedup }}
  dedup: {{ $classOptions.dedup | quote }}
  {{- end }}
  fstype: {{ $classOptions.fstype | default "zfs" }}
  poolname: {{ required "poolName is required for storage class " $classOptions.poolName }}
  {{- if $classOptions.shared }}
  shared: {{ $classOptions.shared | quote }}
  {{- end }}
provisioner: zfs.csi.openebs.io
reclaimPolicy: {{ $classOptions.reclaimPolicy | default "Delete" }}
---
{{- end -}}
{{- end -}}
{{- end -}}
