{{- if and (((.Values).sonarqube).ingress).enabled ((.Values).blackbox).probe }}
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: blackbox-probe-sonarqube
spec:
  interval: 30m
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:19115
  targets:
    staticConfig:
      static:
        {{- range (((.Values).sonarqube).ingress).hosts }}
        - https://{{ .name }}{{ .path }}
        {{- end }}
{{- end}}
