puppetserver:
  puppetserver:
    name: puppetserver
    puppeturl: "https://github.com/Obmondo/LinuxAid.git"
    masters:
      ingress:
        enabled: false

  r10k:
    asSidecar: false

  hiera:
    name: hiera
    hieradataurl: "https://github.com/Obmondo/linuxaid-config-template.git"

  postgresql:
    enabled: false

  puppetdb:
    enabled: true
    name: puppetdb
    extraEnv:
      PUPPETDB_POSTGRES_HOSTNAME: puppetserver-pgsql-rw

  puppetboard:
    enabled: true
    name: puppetboard

  metrics:
    prometheus:
      disableAPICheck: true
      puppetdb:
        enabled: true
      jmx:
        enabled: false

  global:
    postgresql:
      auth:
        existingSecret: puppetserver-pgsql-app
        secretKeys:
          usernameKey: username
          userPasswordKey: password

postgresql:
  instance: 1
  size: 2Gi
  recover: false
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 256Mi
      cpu: 100m

puppetAgentExporter:
  image: harbor.obmondo.com/obmondo/dockerfiles/puppet-agent-exporter
  tag: v0.0.1
  imagePullPolicy: IfNotPresent
  extraEnv:
    METRICS_PATH: /etc/puppetlabs/code/prometheus-dropzone
  resources:
    limits:
      memory: 50Mi
    requests:
      memory: 50Mi
      cpu: 20m
