groups:
  - name: monitor::raid::mdraid
    rules:
      - alert: monitor::raid::mdraid::degraded
        annotations:
          description: |
            RAID array '{{ .Labels.device }}' on {{ .Labels.certname }} is in degraded
            state due to one or more disks failures. Number of spare drives is insufficient
            to fix issue automatically.
          summary: RAID Array is degraded
        expr: |
          (node_md_state{state="inactive"} > 0) * on(instance) group_left (pod) node_uname_info{nodename=~".+"} and on(certname) obmondo_monitoring{alert_id="monitor::raid::mdraid::degraded"} > 0
        for: 15m
        labels:
          severity: critical
          alert_id: monitor::raid::mdraid::degraded

      - alert: monitor::raid::mdraid::failed
        annotations:
          description: |
            At least one device in RAID array on {{ .Labels.certname }} failed.
            Array '{{ .Labels.device }}' needs attention and possibly a disk swap.
          summary: Failed device in RAID array
        expr: |
          (node_md_disks{state="failed"} > 0) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"} and on(certname) obmondo_monitoring{alert_id="monitor::raid::mdraid::failed"} > 0
        for: 15m
        labels:
          severity: critical
          alert_id: monitor::raid::mdraid::failed
