groups:
  - name: monitor::system::service::smartmon
    rules:
    - alert: monitor::system::service::smartmon::smartmon_udma_crc_error_count_raw_value
      expr: |
        smartmon_udma_crc_error_count_raw_value != 0 and on(certname) obmondo_monitoring
      for: 3h
      labels:
        severity: critical
        alert_id: monitor::system::service::smartmon::smartmon_udma_crc_error_count_raw_value
      annotations:
        summary: 'Disk **{{ $labels.disk }}** on **{{ $labels.certname }}** has disk sata failure'
        description: |
          Disk **{{ $labels.disk }}** on **{{ $labels.certname }}** has disk sata failure,
          instance="**{{ $labels.instance }}**",
          type="**{{ $labels.type }}**",

          UDMA_CRC_Error_Count - The number of errors related to data transfer over the interface. A value of **{{ $value }}** is concerning and indicates potential issues with the data cable or connections.
    - alert: monitor::system::service::smartmon::disk_healthy
      expr: |
        smartmon_device_smart_healthy == 0
        and on(certname) obmondo_monitoring{alert_id="monitor::system::service::smartmon::disk_healthy"} > 0
      for: 3h
      labels:
        severity: critical
        alert_id: monitor::system::service::smartmon::disk_healthy
      annotations:
        summary: 'Disk **{{ $labels.disk }}** on **{{ $labels.certname }}** has SMART failure'
        description: 'Disk **{{ $labels.disk }}** on **{{ $labels.certname }}** has SMART failure'
    - alert: monitor::system::service::smartmon::smartmon_reallocated_sector_ct_raw_value
      expr: smartmon_reallocated_sector_ct_raw_value > smartmon_reallocated_sector_ct_threshold and on(certname) obmondo_monitoring
      for: 3h
      labels:
        severity: critical
        alert_id: monitor::system::service::smartmon::smartmon_reallocated_sector_ct_raw_value
      annotations:
        summary: 'Disk **{{ $labels.disk }}** on **{{ $labels.certname }}** has remapped disk sector too many times'
        description: |
          Disk **{{ $labels.disk }}** on **{{ $labels.certname }}** has remapped sector too many times,
          instance="**{{ $labels.instance }}**",
          type="**{{ $labels.type }}**",

          Reallocated Sectors Count -  This value is primarily used as a metric of the life expectancy of the drive; a drive which has had any reallocations at all is significantly more likely to fail in the immediate months.
