groups:
  - name: monitor::system::service::smartmon
    rules:
    - alert: monitor::system::service::smartmon::smartmon_udma_crc_error_count_raw_value
      expr: |
        smartmon_udma_crc_error_count_raw_value != 0 and on(certname) obmondo_monitoring
      for: 3h
      labels:
        severity: critical
        alert_id: monitor::system::service::smartmon::smartmon_udma_crc_error_count_raw_value
      annotations:
        summary: 'Disk **{{ $labels.disk }}** on **{{ $labels.certname }}** has disk sata failure'
        description: |
          Disk **{{ $labels.disk }}** on **{{ $labels.certname }}** has disk sata failure,
          instance="**{{ $labels.instance }}**",
          type="**{{ $labels.type }}**",

          UDMA_CRC_Error_Count - The number of errors related to data transfer over the interface. A value of **{{ $value }}** is concerning and indicates potential issues with the data cable or connections.
