groups:
  - name: monitor::system::service::smartmon
    rules:
    - alert: monitor::system::service::smartmon::disk_healthy
      expr: |
        smartmon_device_smart_healthy == 0
        and on(certname) obmondo_monitoring{alert_id="monitor::system::service::smartmon::disk_healthy"} > 0
      for: 5m
      labels:
        severity: critical
        alert_id: monitor::system::service::smartmon::disk_healthy
      annotations:
        summary: 'Disk **{{ $labels.disk }}** on **{{ $labels.certname }}** has SMART failure'
        description: 'Disk **{{ $labels.disk }}** on **{{ $labels.certname }}** has SMART failure'
