apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  {{- if .Values.postgresql.recover }}
  name: {{ .Release.Name }}-pgsql-recover
  {{- else }}
  name: {{ .Release.Name }}-pgsql
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.postgresql.instance | default 1 }}
  {{- if .Values.postgresql.recover }}
  bootstrap:
    recovery: {{ .Release.Name }}-pgsql
  {{- else }}
  bootstrap:
    initdb:
      database: {{ .Values.postgresql.bootstrap.initdb.database | default "giteadb" }}
      owner: {{ .Values.postgresql.bootstrap.initdb.database | default "giteadb" }}
  {{- end }}
  resources:
    limits:
      memory: {{ .Values.postgresql.resources.limits.memory | default "800Mi" }}
    requests:
      memory: {{ .Values.postgresql.resources.requests.memory | default "500Mi" }}
      cpu: {{ .Values.postgresql.resources.requests.cpu | default "100m" }}
  storage:
    size: {{ .Values.postgresql.size }}
    {{- if .Values.postgresql.storageClass }}
    storageClass: {{ .Values.postgresql.storageClass }}
    {{- end }}
  {{- if .Values.postgresql.recover }}
  externalClusters:
    name: {{ .Release.Name }}-pgsql
    barmanObjectStore:
      destinationPath: {{ .Values.postgresql.backup.destinationPath }}
      endpointURL: {{ .Values.postgresql.backup.endpointURL }}
      {{- if eq .Values.postgresql.backup.cloud "aws" }}
      s3Credentials:
        accessKeyId:
          name: postgresql-psql-backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: postgresql-psql-backup-creds
          key: ACCESS_SECRET_KEY
      {{- end }}
      {{- if eq .Values.postgresql.backup.cloud "azure" }}
      azureCredentials:
        connectionString:
          name: postgresql-psql-backup-creds
          key: AZURE_CONNECTION_STRING
        storageAccount:
          name: postgresql-psql-backup-creds
          key: AZURE_STORAGE_ACCOUNT
        storageKey:
          name: postgresql-psql-backup-creds
          key: AZURE_STORAGE_KEY
        storageSasToken:
          name: postgresql-psql-backup-creds
          key: AZURE_STORAGE_SAS_TOKEN
      {{- end }}
      wal:
        maxParallel: 8
  {{- end }}
  {{- if .Values.postgresql.backup }}
  backup:
    barmanObjectStore:
      destinationPath: {{ .Values.postgresql.backup.destinationPath }}
      endpointURL: {{ .Values.postgresql.backup.endpointURL }}
      {{- if eq .Values.postgresql.backup.cloud "aws" }}
      s3Credentials:
        accessKeyId:
          name: postgresql-psql-backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: postgresql-psql-backup-creds
          key: ACCESS_SECRET_KEY
      {{- end }}
      {{- if eq .Values.postgresql.backup.cloud "azure" }}
      azureCredentials:
        connectionString:
          name: postgresql-psql-backup-creds
          key: AZURE_CONNECTION_STRING
        storageAccount:
          name: postgresql-psql-backup-creds
          key: AZURE_STORAGE_ACCOUNT
        storageKey:
          name: postgresql-psql-backup-creds
          key: AZURE_STORAGE_KEY
        storageSasToken:
          name: postgresql-psql-backup-creds
          key: AZURE_STORAGE_SAS_TOKEN
      {{- end }}
      wal:
        compression: gzip
        encryption: AES256
    retentionPolicy: "30d"
  {{- end }}
